jenkinsci/dependency-check-plugin

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/Options.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/global.jelly, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/global.properties, src/main/webapp/help-database-connstring.html, src/main/webapp/help-database-dbdriver.html, src/main/webapp/help-database-dbpassword.html, src/main/webapp/help-database-dbuser.html, src/main/webapp/help-database-path.html
Improve OWASP DC Jenkins Plugin to allow a customized database
connection configuration, such as to a centralized MySQL or Postgres
vulnerability database. An embedded h2 database is still used by
default to execute the OWASP dependency check if no custom database
configuration is provided.
This is an improved version to use global config instead of per-job config
and replace pull request 4
=> Allow custom database configuration

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java
Avoid the following NullPointerException, which happened to me on version v1.4.4:
```
[DependencyCheck] OWASP Dependency-Check Plugin v1.4.4
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = XXXXXXX-dependencyCheck
[DependencyCheck]  -scanPath = XXXXXXX
[DependencyCheck]  -outputDirectory = XXXXXXX
[DependencyCheck]  -dataDirectory = XXXXXXX
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -proxyServer = XXXXXXX
[DependencyCheck]  -proxyPort = XXXX
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -useMavenArtifactsScanPath = false
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodeJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck] …
```
=> Avoid NullPointerException if exception doesn't have a cause

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/Options.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/config.jelly, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/config.properties, src/main/resources/org/jenkinsci/plugins/DependencyCheck/Messages.properties, src/main/webapp/help-hints-file.html
duplicate how suppression file configuration works for hints file to allow users to add their own hints xml file to dependency-check-core. 
Tested using mvn hpi:run; 
- hintsfile field is there 
- help file is accessible
- verified missing file gets logged, 
- verified valid file gets used
=> adding hintsFile configuration

src/main/java/org/jenkinsci/plugins/DependencyCheck/AbstractDependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/Options.java
* Use the correct method name so the property gets saved when using the `Invoke OWASP Dependency-Check analysis` build step
* Remove false advertising around the verbose log file location
=> Fix verbose logging.

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/config.jelly
Use the correct method names in `config.jelly` so that the flags for the analyzer step get saved and loaded properly.
Note that I changed the method name to `isAutoupdateDisabled` to more closely follow Java method naming conventions.
=> Fix saving the job flags.

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyTrackPublisher.java
This is to avoid exception when running pipeline build on a slave. This seems somewhat related to JENKINS-45782, see https://github.com/jenkinsci/dependency-check-plugin/commit/05f7c6b0677d9db91469a876101b3ee0cdb0c1fa.
```
java.io.NotSerializableException: java.io.PrintStream
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at …
```
=> Make inner class of DependencyTrackPublisher serializable

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyTrackPublisher.java
When people create a project without add the version, jenkins plugin will run error.
That's because the JsonObject can't do with the empty value.
So there are two ways to solve this problems.
1. the plugin could check the value of "version", and set a default value.
2. the track could check the value is or not empty when people create a new project.
=> fix error when the "version" is empty

pom.xml
I was running Plugin Compat Tester for [JEP-200](https://github.com/jenkinsci/jep/tree/master/jep/200). It required updating Plugin POM to the newer version. The update reveals some FindBugs and Javadoc issues in the plugin, but they are suppressed for now.
BTW, the plugin is about having issues with JEP-200. We will investigate it together with @jglick.  https://docs.google.com/document/d/1uQcyaaLvGFwFDe0mQ27JHeG2icdX0XfCHILbHGOtAmA/edit#heading=h.6x165kwmc557 
@reviewbybees
=> Update Plugin POM to the recent version

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/Options.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/global.jelly, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/global.properties, src/main/webapp/help-nodepackage-analyzer-enabled.html
It's impossible now to disable this analyser in the global config.
If I disable NSP analyser, I then have an error  "Message: Invalid Configuration: enabling the Node Package Analyzer without using the NSP Analyzer is not supported."
So it's impossible to perform a dependency check analysis without NSP Analyser activated.
So this pull request adds an option to activate or not the Node Package Analyser.
=> Adding option to disable Node Package Analyser

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyTrackPublisher.java
When no artifact is specified, an empty body is uploaded and the build succeeds without an error/hint.
=> Do not try to upload file if artifact is blank

src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckExecutor.java
@stevespringett Due to changes in how the local H2 database is handled one must close the database (and any open connections) prior to closing the settings. This will ensure that the temp directory can be removed.
Additionally, if we upped the Java source version to 1.7 we could use a try with resources for the engine object.
=> Ensure Temporary Files Deleted

pom.xml
This PR upgrades to the latest version of ODC. The build currently targets a version of Jenkins that contains a vulnerable version of `guava`. As such, we had to exclude the guava (transitive) dependency from odc-core.
Note - the jenkins plugin itself is still at 4.0.2-SNAPSHOT.
=> Upgrade odc-core and utils to 4.0.2

src/main/java/org/jenkinsci/plugins/DependencyCheck/AbstractDependencyCheckBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/config.jelly, src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder/config.properties, src/main/webapp/help-buildResultSuccess-preserve.html
Dependency-Check core used to fail by different reasons: DB misconfiguration, internal bugs, locks etc...
If ODC check is executed in pipeline and it is optional check then we are not intrested in affecting pipeline result. 
Although we could catch and handle all ODC exceptions, we cannot improve build result during handling without using unsecure things as _currentBuild.rawBuild_.
This feature allow to preserve previous state of build in case of scan failure. It wiil be very usefull in companies where pipelines are not single-stage pipelines.
=> Preserve build result state regardless scan success

src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstallation.java
This PR fixes this warning (seen first time one runs a job using a DependencyCheck installation):
```
2020-01-28 13:04:31.960+0000 [id=68]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation$1 in file:/var/lib/jenkins/plugins/dependency-check-jenkins-plugin/WEB-INF/lib/dependency-check-jenkins-plugin.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```
See https://jenkins.io/redirect/serialization-of-anonymous-classes/ for explanations. I think my patch is pretty obvious, and I've tested that the warning goes away with patched version of the plugin.
=> fix attempt to serialize anonymous class (JEP-200)

src/main/java/org/jenkinsci/plugins/DependencyCheck/ResultAction.java
Fixes this warning (when using the `DependencyCheckPublisher`):
```
2020-01-28 14:10:01.010+0000 [id=46]	WARNING	hudson.XmlFile#replaceIfNotAtTopLevel: JENKINS-45892: reference to hudson.model.FreeStyleProject@1fac1ebf[test-js] being saved from unexpected /var/lib/jenkins/jobs/test-js/builds/12/build.xml
```
This comes from changes introduced in 5.1.0 on `ResultAction`: 8a7497b
- the reference to the `Run` has been made non-transient, whereas it was correct to have it as a transient field (you don't want to serialize / self-reference the `Run` itself in the `build.xml`). The [RunAction2](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/RunAction2.java) interface is implemented, and it takes care of having a reference to the Run injected via `onLoad()` when …
=> fix ResultAction serialization (JENKINS-45892)

src/main/resources/org/jenkinsci/plugins/DependencyCheck/JobAction/floatingBox.jelly, src/main/webapp/js/charts.js
For our pipeline, we use another plugin which also uses the `echarts` library. The addition of the Owasp Dependency Trend Chart broke our original chart:
The reason this happens is because of the function shown below. I confirmed this using a `console.log` on the entering `chartDivId`. 
It seems that it is overwriting a globally named function within the `echarts` library itself, as the other Trend Chart (JUnit) never explicitly references that function name anywhere inside the source.  The function appears to be this one (from within `echarts`):
The quickest, simplest fix for this to work was to rename the function:
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ x] Ensure that the pull request title represents the …
=> Bugfix: remove 'echarts' library global namespace pollution

src/main/java/org/jenkinsci/plugins/DependencyCheck/ResultAction.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/ResultProjectAction.java, src/main/resources/org/jenkinsci/plugins/DependencyCheck/ResultProjectAction/jobMain.jelly
To improve accessibility to the latest dependency check report add a new action on the main job page as for the "Last Test Result" that leads to the last dependency-check.
=> [JENKINS-67870] Add project action Latest Dependency-Check

src/main/resources/org/jenkinsci/plugins/DependencyCheck/DependencyCheckToolBuilder/config.jelly
Fixed bug when having multiple installations, the configured version is not selected in the UI.
As reported in [JENKINS-71670](https://issues.jenkins.io/browse/JENKINS-71670), when there are multiple installations of dependency-check available, the configured one is not selected when loading a job in the UI. Because none is selected, the drop-down defaults to selecting the first entry, which might update the job-configuration on save, if it was not the correct selection.
Bug appeared to be a copy-paste issue, where a field-name wasn't changed.
Change was tested manually by having installed 2 versions of DC:
- Create a job, add a DC-run and select the 2nd installation. Save
- Edit the job: before this update, the selected installation shows the 1st, after the fix it shows the 2nd. …
=> Fixed bug when having multiple installations, the configured version is not selected in the UI

src/main/resources/org/jenkinsci/plugins/DependencyCheck/ResultAction/index.jelly, src/main/resources/org/jenkinsci/plugins/DependencyCheck/ResultAction/resource.js
https://issues.jenkins.io/browse/JENKINS-74072
The affected view seems to work fine in the restrictive mode of CSP plugin in the basic testing that I've done.
[Before the change](https://www.youtube.com/watch?v=1lTMYlOUJTc)
[After the change](https://www.youtube.com/watch?v=J67KFrIPEJk)
=> [JENKINS-74072] Extract inline JavaScript from `DependencyCheck/ResultAction/index.jelly`

src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Dependency.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/ReportParser.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/transformer/FindingsTransformer.java, src/test/java/org/jenkinsci/plugins/DependencyCheck/model/ReportParserTest.java
Display project references in OWASP dependency check table.
See [JENKINS-74934](https://issues.jenkins.io/browse/JENKINS-74934) for more information.
Parse "dependency/projectReferences/projectReference" from the dependency-check XML, available in dependency-check.1.7.xsd through dependency-check.4.0.xsd (latest).
Then display the value in the Dependency-Check Reports table, and also make it filterable (searchable). 
Added test-case to verify that XML parsing works fine (see `ReportParserTest.testProjectReferences`)
Deployed plugin to Jenkins installation and verified that the plugin works as intended. 
Note that old jobs that were run with a previous version of the dependency-check plugin will not have the project references value populated in the table. It seems like the parsed Java …
=> JENKINS-74934: Display project references in OWASP dependency check table

pom.xml, src/main/java/org/jenkinsci/plugins/DependencyCheck/AbstractThresholdPublisher.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckPublisher.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckToolBuilder.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/ResultAction.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Analysis.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/CvssV2.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/CvssV3.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Dependency.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Finding.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/ProjectInfo.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Reference.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/RiskGate.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/ScanInfo.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Severity.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/SeverityDistribution.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Thresholds.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/model/Vulnerability.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/pipeline/DependencyCheckStep.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/pipeline/DependencyCheckStepExecutor.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstallation.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstaller.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/Version.java, src/main/java/org/jenkinsci/plugins/DependencyCheck/transformer/FindingsTransformer.java, src/main/resources/index.jelly, src/test/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckToolBuilderTest.java, src/test/java/org/jenkinsci/plugins/DependencyCheck/aggregator/FindingsAggregatorTest.java, src/test/java/org/jenkinsci/plugins/DependencyCheck/casc/JCasCTest.java, src/test/java/org/jenkinsci/plugins/DependencyCheck/transformer/FindingsTransformerTest.java
Jenkins 2.479.1 provides Jakarta EE 9, Eclipse Jetty 12, Spring Security 6, and Java 17.
* Update plugin pom and baseline
* Remove deprecations
* Use Java 17 language features
Confirmed that tests pass.
=> Require Jenkins 2.479.1 and Jakarta EE 9
